{{- if .Values.enabled }}
{{- if not .Values.auth.existingSecret }}
# MongoDB Auth Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword }}
{{- end }}
{{- end }}
